# Generated by Django 3.2.23 on 2025-03-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='DotaHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dota_id', models.CharField(max_length=255, unique=True)),
                ('thumbnail_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dota_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualGameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiant_side', models.BooleanField()),
                ('won_game', models.BooleanField()),
                ('base_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_appearances', to='idl_tracker.baseteam')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='idl_tracker.game')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('best_of', models.PositiveSmallIntegerField(choices=[(2, 'Best of 2'), (3, 'Best of 3')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steam_id', models.CharField(max_length=255, unique=True)),
                ('avatar_url', models.URLField(unique=True)),
                ('elo', models.IntegerField()),
                ('elo_last_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('draft_format', models.CharField(choices=[('captains_mode', "Captain's Mode"), ('captains_draft', "Captain's Draft")], default='captains_mode', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idl_tracker.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idl_tracker.baseteam')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CORE', 'Core (pos 1-3)'), ('LIGHT_SUPPORT', 'Soft Support (pos 4)'), ('HARD_SUPPORT', 'Hard Support (pos 5)')], max_length=50)),
                ('kills', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('stratz_imp_score', models.SmallIntegerField()),
                ('experience_per_minute', models.IntegerField()),
                ('gold_per_minute', models.IntegerField()),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='idl_tracker.dotahero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='idl_tracker.individualgameteam')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='idl_tracker.season'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches_played', through='idl_tracker.TeamParticipation', to='idl_tracker.BaseTeam'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='idl_tracker.match'),
        ),
        migrations.AddField(
            model_name='baseteam',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_captained', to='idl_tracker.player'),
        ),
        migrations.AddField(
            model_name='baseteam',
            name='players',
            field=models.ManyToManyField(related_name='teams_joined', to='idl_tracker.Player'),
        ),
        migrations.AddField(
            model_name='baseteam',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_drafted', to='idl_tracker.season'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipation',
            constraint=models.UniqueConstraint(fields=('team', 'match'), name='no_duplicate_teams'),
        ),
        migrations.AddConstraint(
            model_name='individualgameteam',
            constraint=models.UniqueConstraint(fields=('game', 'radiant_side'), name='different_sides'),
        ),
        migrations.AddConstraint(
            model_name='individualgameteam',
            constraint=models.UniqueConstraint(fields=('game', 'won_game'), name='only_one_winner'),
        ),
    ]
